### ISSUE TITLE
Tree cutter bot fails

### ISSUE THREAD

**Issue by PordyHUN** [Yoplitein/WurmHelper#6]
Tree cutter bot stops working all the time.

TreeCutterBot is on!
=== TreeCutterBot ===
Cuts trees
Usage: bot tc {a|al|area|area_speed|axe|b|c|info|off|pause|s|sp|t|tt}
Current threshold for stamina is 0.96
TreeCutterBot will do 6 chops each time
TreeCutterBot will use hatchet, steel with QL:98.881294 DMG:0.036097392
Minimal tree age set to overaged!
Set tree types for chopping. Chop all trees by default
Current threshold for stamina is 0.4
TreeCutterBot has encountered an error - null
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1701)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.ildar.wurm.bot.TreeCutterBot.work(TreeCutterBot.java:117)
	at net.ildar.wurm.bot.Bot.run(Bot.java:39)
TreeCutterBot was stopped**

**Comment by Yoplitein** [comment]
It seems to be choking trying to check for trees with beehives, which isn't uncommon for tasks that have to inspect ground items. Odd that I've never run into this case specifically though, despite clear-cutting many forests full of hives. Try [this build](https://github.com/user-attachments/files/16550426/WurmHelperFix.zip) and let me know whether that fixes it.

**Comment by PordyHUN** [comment]
=== TreeCutterBot ===
Cuts trees
Current threshold for stamina is 0.96
TreeCutterBot will do 3 chops each time
Usage: bot tc {a|al|area|area_speed|axe|b|c|info|off|pause|s|sp|t|tt}
TreeCutterBot will use hatchet, steel (B80) with QL:90.881294 DMG:0.2856138
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
	at java.util.HashMap.putMapEntries(HashMap.java:512)
	at java.util.HashMap.<init>(HashMap.java:490)
	at net.ildar.wurm.bot.TreeCutterBot.work(TreeCutterBot.java:110)
	at net.ildar.wurm.bot.Bot.run(Bot.java:39)
TreeCutterBot has encountered an error - null
java.util.ConcurrentModificationException
TreeCutterBot was stopped
