### ISSUE TITLE
Bulk Item Getter Bot cant get items if the SSXY target has lower number than the bot wants to move to maintain the item number level.

### ISSUE THREAD

**Issue by PordyHUN** [Yoplitein/WurmHelper#7]
If you use the "SSXY" command because you want to move things from a sorted container with various Quality levels, when the remaining items are less than the number you setup for the maintain level (for example, you want to keep 5 stone bricks in your inventory, but the Q25 stone brick has only 3 left) the bot cannot cope with the situation.

There is a workaround to setup the maintain level to 2 and lower the timeout to minimum, and even if  you craft f.e. stone bricks from rock shards you always have 1 rockshard in your inventory and the bot only have to move rock shards one by one, so even the last remaing could be pulled, but even so a stone brick crafting on high level a bit faster than this could work.

**Comment by PordyHUN** [comment]
Occasionally the even stops with an error:
In this case t was set to 100

More than one item found, defaulting to the first
Source is now: stone brick (1x)
Timed out after 5 seconds waiting for bulk item transfer question
Source is now: stone brick (8x)
Source is now: stone brick (8x)
Source is now: stone brick (7x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
Source is now: stone brick (6x)
BulkItemGetterBot has encountered an error - null
java.lang.NullPointerException
java.lang.NullPointerException
	at net.ildar.wurm.Utils.getInventoryItemsAtPoint(Utils.java:411)
	at net.ildar.wurm.bot.ItemSpec.updateSource(BulkItemGetterBot.java:332)
	at net.ildar.wurm.bot.ItemSpec.updateSource(BulkItemGetterBot.java:326)
	at net.ildar.wurm.bot.BulkItemGetterBot.work(BulkItemGetterBot.java:61)
	at net.ildar.wurm.bot.Bot.run(Bot.java:39)
BulkItemGetterBot was stopped
